name: Codex Full Repo Review

on:
  # 👇 Run manually or automatically on pushes to main
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  full-review:
    runs-on: ubuntu-latest
    steps:
      # Step 1 — Checkout your repo code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 — Setup Node.js 20+
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3 — Install dependencies
      - name: Install dependencies
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm install @openai/codex-sdk

      # Step 4 — Confirm API key secret is available
      - name: Check for OPENAI_API_KEY secret
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "❌ Missing OPENAI_API_KEY secret. Please add it under Settings → Secrets → Actions."
            exit 1
          else
            echo "✅ OPENAI_API_KEY found. Proceeding..."
          fi

      # Step 5 — Run Codex full repository review
      - name: Run Codex Full Repo Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node .github/tools/codex-full-review.mjs

      # Step 6 — Upload output artifacts
      - name: Upload Codex Review Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: codex-full-review
          path: |
            codex_full_review.json
            codex_full_review.md
